use_frameworks!

platform :ios, '8.0'

target 'SYZPersonalPageViewController_Example' do
  pod 'SYZPersonalPageViewController', :path => '../'
  pod 'Masonry'
  pod 'ReactiveObjC'
  pod 'YYWebImage'
  
  target 'SYZPersonalPageViewController_Tests' do
    inherit! :search_paths
  
  end
end
